spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nuovoStudent
    username: root
    password: Giosal21,.MySQL
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
